image: node:10

cache:
  key: $CI_COMMIT_REF_SLUG
  paths:
    - node_modules/

stages:
  - setup
  - test
  - release

#########
# SETUP #
#########
setup:
  stage: setup
  script:
    - yarn install --frozen-lockfile
  artifacts:
    paths:
      - node_modules/

########
# TEST #
########
lint:
  stage: test
  cache:
    policy: pull
  script:
    - yarn lint

test:
  stage: test
  cache:
    policy: pull
  script:
    - cp .env.example .env
    - yarn test

###############
# NPM RELEASE #
###############
release:
  stage: release
  cache:
    policy: pull
  only:
    - master
  script:
    - /bin/sh $(pwd)/scripts/ci-release.sh
